version: "3"

services:
  node-app:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: npm run dev # dit is niet productiewaardig, probeer een verschil te maken tussen dev en prod
  
  frontend-dashboard:
    build: 
      context: frontend-dashboard
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend-dashboard/:/app
    ports:
      - 3000:3000
    command: npm run dev # dit is niet productiewaardig, probeer een verschil te maken tussen dev en prod
    depends_on:
      - node-app 
volumes:
  mongo-db:
