version: "3"

services:
  node-app:
    container_name: node-app
    build: .
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
    env_file:
      - ./.env
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: npm run dev
    depends_on:
      - mongo 
 
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-db:/data/db
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
   
  # frontend-app:
  #   container_name: frontend-app
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongo


volumes:
  mongo-db:
