version: "3"

services:
  node-app:
    container_name: node-app
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
