version: '3'

services:
  node_app:
    env_file:
      - ./.env
    environment:
      - MONGO_USER=${MONGO_USER_DEV}
      - MONGO_PASSWORD=${MONGO_PASSWORD_DEV}
    command: npm run dev

  frontend_dashboard:
    command: npm run dev
    environment:
      - NODE_ENV=dev

  mongo_db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_DEV}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD_DEV}
      - MONGO_INITDB_DATABASE=${DB_NAME}

  mongo_express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER_DEV}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD_DEV}
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME_DEV}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_ADMIN_DEV}
    depends_on:
      - node_app

  frontend_app:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 19006:19006
      - 19002:19002
    volumes:
      - ../frontend/:/app/
      - /app/node_modules
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - node_app
