version: '3'

services:
  node_app:
    env_file:
      - ./.env
    command: npm run dev
    environment:
      - MONGO_USER=${MONGO_USER_PROD}
      - MONGO_PASSWORD=${MONGO_PASSWORD_PROD}
      - NODE_ENV=production

  frontend_dashboard:
    command: npm run start

  mongo_db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_PROD}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD_PROD}
      - MONGO_INITDB_DATABASE=${DB_NAME} 