version: '3'

services:
  node_app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../backend/:/app
      - /app/node_modules
    ports:
      - 5000:5000

  frontend_dashboard:
    build:
      context: ../frontend-dashboard
      dockerfile: Dockerfile
    volumes:
      - ../frontend-dashboard/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - node_app

  mongo_db:
    image: mongo:5.0.1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../mongo_db:/data/db

volumes:
  mongo_db:
