version: '3'

services:
  node_app:
    env_file:
      - ./.env
    environment:
      - MONGO_USER=${MONGO_USER_PROD}
      - MONGO_PASSWORD=${MONGO_PASSWORD_PROD}
    command: npm run dev

  frontend_dashboard:
    command: ['npm run build && npm run start']

  mongo_db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_PROD}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD_PROD}
      - MONGO_INITDB_DATABASE=${DB_NAME}

  mongo_express:
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER_PROD}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD_PROD}
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME_PROD}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_ADMIN_PROD}

  frontend_app:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
